/* DO NOT EDIT, file generated by nestjs-i18n */

import type { Path } from 'nestjs-i18n';

export type I18nTranslations = {
	exceptions: {
		auth: {
			invalidEmailOrPassword: string;
		};
		users: {
			emailIsAlreadyRegistered: string;
		};
	};
};
export type I18nPath = Path<I18nTranslations>;
