/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/users': {
		get: operations['UsersController_getUsers'];
		post: operations['UsersController_create'];
	};
	'/users/me/teams': {
		get: operations['UsersController_findAllTeams'];
	};
	'/users/me/conversations': {
		get: operations['UsersController_findAllConversations'];
	};
	'/teams': {
		post: operations['TeamsController_create'];
	};
	'/conversations': {
		post: operations['ConversationsController_create'];
	};
	'/conversations/{id}/messages': {
		get: operations['ConversationsController_getMessages'];
		post: operations['ConversationsController_createMessage'];
	};
	'/sessions': {
		post: operations['SessionsController_create'];
	};
	'/sessions/me': {
		get: operations['SessionsController_getCurrent'];
		delete: operations['SessionsController_deleteCurrent'];
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {
		CreateUserDto: {
			fullName: string;
			email: string;
			password: string;
		};
		UserDto: {
			id: number;
			fullName: string;
			email: string;
		};
		OpenAPIHttpException: {
			statusCode: number;
			message: string;
			error: string;
		};
		FoundUserDto: {
			id: number;
			fullName: string;
		};
		TeamDto: {
			id: number;
			name: string;
			description: string;
		};
		ConversationDto: {
			id: string;
			name: string | null;
		};
		CreateTeamDto: {
			name: string;
			description: string;
		};
		CreateConversationDto: {
			memberIds: number[];
		};
		CreateMessageDto: {
			content: string;
		};
		MessageDto: {
			id: number;
			author: components['schemas']['FoundUserDto'];
			content: string;
		};
		CreateSessionDto: {
			email: string;
			password: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
	UsersController_getUsers: {
		parameters: {
			query: {
				search: string;
			};
		};
		responses: {
			/** @description Returns found users */
			200: {
				content: {
					'application/json': components['schemas']['FoundUserDto'][];
				};
			};
			/** @description You are not authenticated */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	UsersController_create: {
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateUserDto'];
			};
		};
		responses: {
			/** @description User has been created */
			201: {
				content: {
					'application/json': components['schemas']['UserDto'];
				};
			};
			/** @description Email is already registered */
			409: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	UsersController_findAllTeams: {
		responses: {
			/** @description Returns a list of the current user's teams */
			200: {
				content: {
					'application/json': components['schemas']['TeamDto'][];
				};
			};
			/** @description You are not authenticated */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	UsersController_findAllConversations: {
		responses: {
			/** @description Returns a list of the current user's conversations */
			200: {
				content: {
					'application/json': components['schemas']['ConversationDto'][];
				};
			};
			/** @description You are not authenticated */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	TeamsController_create: {
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateTeamDto'];
			};
		};
		responses: {
			/** @description Team has been created */
			201: {
				content: {
					'application/json': components['schemas']['TeamDto'];
				};
			};
			/** @description You are not authenticated */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	ConversationsController_create: {
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateConversationDto'];
			};
		};
		responses: {
			/** @description Conversation has been created */
			201: {
				content: {
					'application/json': components['schemas']['ConversationDto'];
				};
			};
			/** @description You are not authenticated */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
			/** @description Something went wrong */
			409: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	ConversationsController_getMessages: {
		parameters: {
			query?: {
				before?: number;
			};
			path: {
				id: string;
			};
		};
		responses: {
			/** @description Returns last messages */
			200: {
				content: {
					'application/json': components['schemas']['MessageDto'][];
				};
			};
			/** @description You are not authenticated */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
			/** @description You are not a member of this conversation */
			409: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	ConversationsController_createMessage: {
		parameters: {
			path: {
				id: string;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateMessageDto'];
			};
		};
		responses: {
			/** @description Message has been created */
			201: {
				content: {
					'application/json': components['schemas']['MessageDto'];
				};
			};
			/** @description You are not authenticated */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
			/** @description Something went wrong or you are not a member of this conversation */
			409: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	SessionsController_create: {
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateSessionDto'];
			};
		};
		responses: {
			/** @description Session has been created */
			201: {
				content: {
					'application/json': components['schemas']['UserDto'];
				};
			};
			/** @description Invalid email or password */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	SessionsController_getCurrent: {
		responses: {
			/** @description Returns the user associated with the current session */
			200: {
				content: {
					'application/json': components['schemas']['UserDto'];
				};
			};
			/** @description You are not authenticated */
			401: {
				content: {
					'application/json': components['schemas']['OpenAPIHttpException'];
				};
			};
		};
	};
	SessionsController_deleteCurrent: {
		responses: {
			200: never;
			/** @description The current session has been created */
			204: never;
		};
	};
}
