name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Run linters
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Run e2e tests
        run: pnpm --filter=api test:e2e
